-- 코드를 입력하세요
SELECT a.ANIMAL_ID, a.ANIMAL_TYPE, a.NAME FROM ANIMAL_INS a LEFT JOIN ANIMAL_OUTS b USING(ANIMAL_ID)
WHERE a.SEX_UPON_INTAKE LIKE "Intact%" and b.SEX_UPON_OUTCOME NOT LIKE "Intact%"
ORDER BY a.ANIMAL_ID